### ISSUE TITLE
Feature request: Offer a printable version?

### ISSUE THREAD

**Issue by rubin110** [MaZderMind/campmap#2]
Any chance you could spit out a version that's printable? SVG or some other format one could send to a plotter would be awesome. :D

Thanks!

**Comment by MaZderMind** [comment]
There is a button for a hi-res png in the tools box for this.

**Comment by rubin110** [comment]
Oh neat! Thank you! I think this would work for a plotter, but if it's just
as easy to produce a vector file that would be awesome!

Also it is unfortunately missing a couple of labels, such as Norton's
Embassy and things like the bathrooms.

**Comment by MaZderMind** [comment]
It is complicated to export to svg or pdf, because the rendering is done in multiple layers and then combined. To render to pdf i'd need to render to multiple pdfs and overlay them afterwards. I added the amenities to the hires export, that should be good enough for printing ;)

**Comment by sknebel** [comment]
@rubin110 did you see that next to the map linked in the announcement e-mail there were other PDF variants as well? Maybe you can edit one of these to fit your needs, since they seem  to be vector based? http://www.physik.tu-berlin.de/~lasse/camp/maps/
